var css = (function () {
	 var c = [ /^\s*inherit\s+$/i, /^\s*(?:#(?:[0-9a-f]{3}){1,2}|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow|transparent|inherit)\s+$/i, /^\s*(?:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset|inherit)\s+$/i, /^\s*(?:thin|medium|thick|0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|inherit)\s+$/i, /^\s*(?:none|inherit)\s+$/i, /^\s*(?:url\("[^\(\)\\\"\r\n]+"\)|none|inherit)\s+$/i, /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:\d+(?:\.\d+)?)%|auto|inherit)\s+$/i, /^\s*(?:0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:[+-]\d+(?:\.\d+)?)%|none|inherit)\s+$/i, /^\s*(?:0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:[+-]\d+(?:\.\d+)?)%|inherit)\s+$/i, /^\s*(?:auto|always|avoid|left|right|inherit)\s+$/i, /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)m?s|0|(?:\d+(?:\.\d+)?)%|inherit)\s+$/i, /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)|inherit)\s+$/i, /^\s*(?:normal|0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|inherit)\s+$/i ];
	 return {
	   'azimuth': /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)(?:deg|g?rad)|leftwards|rightwards|inherit)\s+$/i,
	   'background': c[ 0 ],
	   'background-attachment': /^\s*(?:scroll|fixed|inherit)\s+$/i,
	   'background-color': c[ 1 ],
	   'background-image': c[ 5 ],
	   'background-position': /^\s*(?:(?:0|(?:\d+(?:\.\d+)?)%|0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|left|center|right)\s+(?:(?:0|(?:\d+(?:\.\d+)?)%|0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|top|center|bottom)\s+)?|inherit\s+)$/i,
	   'background-repeat': /^\s*(?:repeat|repeat-x|repeat-y|no-repeat|inherit)\s+$/i,
	   'border': c[ 0 ],
	   'border-bottom': c[ 0 ],
	   'border-bottom-color': c[ 1 ],
	   'border-bottom-style': c[ 2 ],
	   'border-bottom-width': c[ 3 ],
	   'border-collapse': /^\s*(?:collapse|separate|inherit)\s+$/i,
	   'border-color': /^\s*(?:(?:(?:#(?:[0-9a-f]{3}){1,2}|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow|transparent)\s+){1,4}|inherit\s+)$/i,
	   'border-left': c[ 0 ],
	   'border-left-color': c[ 1 ],
	   'border-left-style': c[ 2 ],
	   'border-left-width': c[ 3 ],
	   'border-right': c[ 0 ],
	   'border-right-color': c[ 1 ],
	   'border-right-style': c[ 2 ],
	   'border-right-width': c[ 3 ],
	   'border-spacing': /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)\s+(?:0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)\s+)?|inherit\s+)$/i,
	   'border-style': /^\s*(?:(?:(?:none|hidden|dotted|dashed|solid|double|groove|ridge|inset|outset)\s+){1,4}|inherit\s+)$/i,
	   'border-top': c[ 0 ],
	   'border-top-color': c[ 1 ],
	   'border-top-style': c[ 2 ],
	   'border-top-width': c[ 3 ],
	   'border-width': /^\s*(?:(?:(?:thin|medium|thick|0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc))\s+){1,4}|inherit\s+)$/i,
	   'bottom': c[ 6 ],
	   'caption-side': /^\s*(?:top|bottom|inherit)\s+$/i,
	   'clear': /^\s*(?:none|left|right|both|inherit)\s+$/i,
	   'clip': /^\s*(?:auto|inherit)\s+$/i,
	   'color': /^\s*(?:#(?:[0-9a-f]{3}){1,2}|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow|inherit)\s+$/i,
	   'counter-increment': c[ 4 ],
	   'counter-reset': c[ 4 ],
	   'cue': c[ 0 ],
	   'cue-after': c[ 5 ],
	   'cue-before': c[ 5 ],
	   'cursor': /^\s*(?:(?:url\("[^\(\)\\\"\r\n]+"\)\s+,\s+)*(?:auto|crosshair|default|pointer|move|e-resize|ne-resize|nw-resize|n-resize|se-resize|sw-resize|s-resize|w-resize|text|wait|help|progress)|inherit)\s+$/i,
	   'direction': /^\s*(?:ltr|rtl|inherit)\s+$/i,
	   'display': /^\s*(?:inline|block|list-item|run-in|inline-block|table|inline-table|table-row-group|table-header-group|table-footer-group|table-row|table-column-group|table-column|table-cell|table-caption|none|inherit)\s+$/i,
	   'elevation': /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)(?:deg|g?rad)|below|level|above|higher|lower|inherit)\s+$/i,
	   'empty-cells': /^\s*(?:show|hide|inherit)\s+$/i,
	   'float': /^\s*(?:left|right|none|inherit)\s+$/i,
	   'font': /^\s*(?:caption|icon|menu|message-box|small-caption|status-bar|inherit)\s+$/i,
	   'font-family': /^\s*(?:(?:"\w(?:[\w-]*\w)(?:\s+\w([\w-]*\w))*"|serif|sans-serif|cursive|fantasy|monospace)\s+(?:,\s+(?:"\w(?:[\w-]*\w)(?:\s+\w([\w-]*\w))*"|serif|sans-serif|cursive|fantasy|monospace)\s+)*|inherit\s+)$/i,
	   'font-size': /^\s*(?:xx-small|x-small|small|medium|large|x-large|xx-large|(?:small|larg)er|0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:[+-]\d+(?:\.\d+)?)%|inherit)\s+$/i,
	   'font-style': /^\s*(?:normal|italic|oblique|inherit)\s+$/i,
	   'font-variant': /^\s*(?:normal|small-caps|inherit)\s+$/i,
	   'font-weight': /^\s*(?:normal|bold|bolder|lighter|100|200|300|400|500|600|700|800|900|inherit)\s+$/i,
	   'height': c[ 6 ],
	   'left': c[ 6 ],
	   'letter-spacing': c[ 12 ],
	   'line-height': /^\s*(?:normal|0|(?:\d+(?:\.\d+)?)|0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:[+-]\d+(?:\.\d+)?)%|inherit)\s+$/i,
	   'list-style': c[ 0 ],
	   'list-style-image': c[ 5 ],
	   'list-style-position': /^\s*(?:inside|outside|inherit)\s+$/i,
	   'list-style-type': /^\s*(?:disc|circle|square|decimal|decimal-leading-zero|lower-roman|upper-roman|lower-greek|lower-latin|upper-latin|armenian|georgian|lower-alpha|upper-alpha|none|inherit)\s+$/i,
	   'margin': /^\s*(?:(?:(?:0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:\d+(?:\.\d+)?)%|auto)\s+){1,4}|inherit\s+)$/i,
	   'margin-bottom': c[ 6 ],
	   'margin-left': c[ 6 ],
	   'margin-right': c[ 6 ],
	   'margin-top': c[ 6 ],
	   'max-height': c[ 7 ],
	   'max-width': c[ 7 ],
	   'min-height': c[ 8 ],
	   'min-width': c[ 8 ],
	   'outline': c[ 0 ],
	   'outline-color': /^\s*(?:#(?:[0-9a-f]{3}){1,2}|aqua|black|blue|fuchsia|gray|green|lime|maroon|navy|olive|purple|red|silver|teal|white|yellow|invert|inherit)\s+$/i,
	   'outline-style': c[ 2 ],
	   'outline-width': c[ 3 ],
	   'overflow': /^\s*(?:visible|hidden|scroll|auto|inherit)\s+$/i,
	   'padding': /^\s*(?:(?:(?:0|(?:\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:[+-]\d+(?:\.\d+)?)%)\s+){1,4}|inherit\s+)$/i,
	   'padding-bottom': c[ 8 ],
	   'padding-left': c[ 8 ],
	   'padding-right': c[ 8 ],
	   'padding-top': c[ 8 ],
	   'page-break-after': c[ 9 ],
	   'page-break-before': c[ 9 ],
	   'page-break-inside': /^\s*(?:avoid|auto|inherit)\s+$/i,
	   'pause': /^\s*(?:(?:(?:0|(?:[+-]\d+(?:\.\d+)?)m?s|0|(?:\d+(?:\.\d+)?)%)\s+){1,2}|inherit\s+)$/i,
	   'pause-after': c[ 10 ],
	   'pause-before': c[ 10 ],
	   'pitch': /^\s*(?:0|(?:\d+(?:\.\d+)?)k?Hz|x-low|low|medium|high|x-high|inherit)\s+$/i,
	   'pitch-range': c[ 11 ],
	   'play-during': /^\s*(?:auto|none|inherit)\s+$/i,
	   'position': /^\s*(?:static|relative|absolute|fixed|inherit)\s+$/i,
	   'quotes': c[ 4 ],
	   'richness': c[ 11 ],
	   'right': c[ 6 ],
	   'speak': /^\s*(?:normal|none|spell-out|inherit)\s+$/i,
	   'speak-header': /^\s*(?:once|always|inherit)\s+$/i,
	   'speak-numeral': /^\s*(?:digits|continuous|inherit)\s+$/i,
	   'speak-punctuation': /^\s*(?:code|none|inherit)\s+$/i,
	   'speech-rate': /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)|x-slow|slow|medium|fast|x-fast|faster|slower|inherit)\s+$/i,
	   'stress': c[ 11 ],
	   'table-layout': /^\s*(?:auto|fixed|inherit)\s+$/i,
	   'text-align': /^\s*(?:left|right|center|justify|inherit)\s+$/i,
	   'text-decoration': c[ 4 ],
	   'text-indent': /^\s*(?:0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|0|(?:\d+(?:\.\d+)?)%|inherit)\s+$/i,
	   'text-transform': /^\s*(?:capitalize|uppercase|lowercase|none|inherit)\s+$/i,
	   'top': c[ 6 ],
	   'unicode-bidi': /^\s*(?:normal|embed|bidi-override|inherit)\s+$/i,
	   'vertical-align': /^\s*(?:baseline|sub|super|top|text-top|middle|bottom|text-bottom|0|(?:\d+(?:\.\d+)?)%|0|(?:[+-]\d+(?:\.\d+)?)(?:em|ex|px|in|cm|mm|pt|pc)|inherit)\s+$/i,
	   'visibility': /^\s*(?:visible|hidden|collapse|inherit)\s+$/i,
	   'voice-family': /^\s*(?:(?:(?:"\w(?:[\w-]*\w)(?:\s+\w([\w-]*\w))*"|male|female|child)\s+,\s+)*(?:"\w(?:[\w-]*\w)(?:\s+\w([\w-]*\w))*"|male|female|child)|inherit)\s+$/i,
	   'volume': /^\s*(?:0|(?:\d+(?:\.\d+)?)|0|(?:[+-]\d+(?:\.\d+)?)%|silent|x-soft|soft|medium|loud|x-loud|inherit)\s+$/i,
	   'white-space': /^\s*(?:normal|pre|nowrap|pre-wrap|pre-line|inherit)\s+$/i,
	   'word-spacing': c[ 12 ],
	   'z-index': /^\s*(?:auto|\d+|inherit)\s+$/i
	 };
   })();